### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by fangaiqing** [DJI-Mobile-SDK-Tutorials/iOS-FPVDemo#1]
when I connected the RC to the mobile device , the demo crashed immediately.
![crash](https://cloud.githubusercontent.com/assets/16395946/11951887/a7ea177e-a8cf-11e5-9e51-2c9c56afae5a.jpg)

**Comment by oliverou** [comment]
Hi, from the screenshot you show, it seems it's an Android problem, please refer it to the Android-FPVDemo issues. Thanks!

**Comment by fangaiqing** [comment]
OK, thank you~

**Comment by oliverou** [comment]
The issue belongs to Android, I will close it. Thanks!
