### ISSUE TITLE
No FPVDemo implementation for swift

### ISSUE THREAD

**Issue by dwcares** [DJI-Mobile-SDK-Tutorials/iOS-FPVDemo#11]
this is important because the data types are different in Swift 3 and it can be tricky to translate from the sample that's on the website in objective

**Comment by dwcares** [comment]
i created a swift implementation and tested it on a mavicpro, i'm happy to submit a PR if you make an empty repo for me. @oliverou @dji-dev 

https://github.com/dwcares/iOS-FPVDemo-Swift

**Comment by oliverou** [comment]
@dwcares , thanks for your contributions. I help to create a repo for FPVDemo-Swift project and mention you in the README file, please check here: <https://github.com/DJI-Mobile-SDK-Tutorials/iOS-FPVDemo-Swift>. If you have any feedbacks or improvements, please submit a PR for us to review. Thanks!

**Comment by dwcares** [comment]
@oliverou thank you for the shout out!!!

**Comment by tfannon** [comment]
thank you @dwcares
