### ISSUE TITLE
cocoapods？

### ISSUE THREAD

**Issue by misuqian** [DJI-Mobile-SDK-Tutorials/iOS-FPVDemo#2]
wish DJI-Mobile-SDK can add cocoapods version

**Comment by cuijiemmx** [comment]
+1

**Comment by dji-dev** [comment]
Hi! Thanks for your suggestions, we will consider to add cocoapods support for iOS SDK soon.

**Comment by oliverou** [comment]
Hi, DJI iOS SDK 3.1.1 is now available on Cocoapods, here is the link: https://cocoapods.org/pods/DJI-SDK-iOS

**Comment by oliverou** [comment]
Since the problem is fixed, I will close this issue. Thanks!
