### ISSUE TITLE
Undefined symbols for architecture i386 , Xcode 7.2.1

### ISSUE THREAD

**Issue by mohammedDehairy** [DJI-Mobile-SDK-Tutorials/iOS-FPVDemo#3]
when i try to add the VideoPreviewer folder to my project , this error appears : 
<img width="739" alt="screen shot 2016-03-13 at 1 29 53 pm" src="https://cloud.githubusercontent.com/assets/2619933/13728655/f2404146-e91f-11e5-83af-fd49604ecce4.png">

this is the VideoPreviewer folder in my project :

<img width="249" alt="screen shot 2016-03-13 at 1 32 22 pm" src="https://cloud.githubusercontent.com/assets/2619933/13728658/13b756de-e920-11e5-8e3d-7d55dee39c12.png">

**Comment by dji-dev** [comment]
Hi, for the FPVDemo project, we don't have libDJIVTH264Decoder.a file, you don't need them to run the FPVDemo, please delete the DJIH264Decoder files and check the project settings compared to the lastest FPVDemo Github source code .
