### ISSUE TITLE
FPVDemo not working with A3 FLIGHT CONTROLLER

### ISSUE THREAD

**Issue by alexandrubichis** [DJI-Mobile-SDK-Tutorials/iOS-FPVDemo#8]
Hello,

I've build the demo and no stream available when I run with my A3 flight controller (the app is registered successfully). There is no issue running with my Phantom.

**Comment by dji-dev** [comment]
Hi, currently, the iOS SDK 3.2 (Which is used by FPVDemo) doesn't support A3 Flight Controller and Light Bridge 2 yet, we will support  them very soon.

**Comment by alexandrubichis** [comment]
On Android-FPV-Demo sample the FPV is working. The problem that I have with android platform is  comunication with onboard device.  Do you have any information why on Android, Transparent Transmission with A3 and LB2 is not working? I also found this thread on dji forum http://forum.dev.dji.com/forum.php?mod=viewthread&tid=32531.

**Comment by alexandrubichis** [comment]
Hi. I still have this issue with the latest Mobile SDK. According to the release notes, A3 with Lightbridge 2 is listed as supported product. Can you help me with this?
