### ISSUE TITLE
Tutorial Missing Step

### ISSUE THREAD

**Issue by brianantonelli** [DJI-Mobile-SDK-Tutorials/iOS-FPVDemo#9]
The tutorial on your website is missing a critical step regarding the video streaming. The user is never instructed anywhere in the tutorial to start the video preview instance (`[[VideoPreviewer instance] start];`) like it should in the `sdkManagerDidRegisterAppWithError` method. I'd do a PR but I dont think your tutorials are on :octocat:

**Comment by dji-dev** [comment]
Hi @brianantonelli, thanks for your feedbacks! We have updated the FPVDemo tutorial on the website, please check the [Working on the DJICameraViewController](https://developer.dji.com/cn/mobile-sdk/documentation/ios-tutorials/index.html#working-on-the-djicameraviewcontroller) section. BTW, if you want to help create a PR, you can help to work on this [Mobile-SDK-Doc](https://github.com/dji-sdk/Mobile-SDK-Doc) github repo. Hope this help!

**Comment by brianantonelli** [comment]
Thanks!
